version: "3.9"
services:
  legion-arch:
    build:
      context: ..
      dockerfile: deploy/docker_testing/Dockerfile.arch
  legion-manjaro:
    build:
      context: ..
      dockerfile: deploy/docker_testing/Dockerfile.arch
      args:
        - "BASE_IMAGE=manjarolinux/base"
  legion-fedora:
    build:
      context: ..
      dockerfile: deploy/docker_testing/Dockerfile.fedora
  # legion-suse:
  #   build:
  #     context: ..
  #     dockerfile: deploy/Dockerfile.suse
  legion-ubuntu:
    build:
      context: ..
      dockerfile: deploy/docker_testing/Dockerfile.ubuntu
  ubuntu:
    image: ubuntu:latest
    volumes:
      - "../../:/app/LenovoLegionLinux"
