version: "3.9"
services:
  legion-arch:
    build:
      context: ../..
      dockerfile: deploy/package_testing/Dockerfile.arch
  legion-manjaro:
    build:
      context: ../..
      dockerfile: deploy/package_testing/Dockerfile.arch
      args:
        - "BASE_IMAGE=manjarolinux/base"
  legion-fedora:
    build:
      context: ../..
      dockerfile: deploy/package_testing/Dockerfile.fedora
  legion-ubuntu:
    build:
      context: ../..
      dockerfile: deploy/package_testing/Dockerfile.ubuntu
    volumes:
      - "../../:/app/LenovoLegionLinux"
    