FROM fedora:39

# does not work
# FROM redhat/ubi9

# ROM rockylinux:8

# does not work (kernel version mismatch->package mismatch)
# FROM rockylinux:8

ARG DEBIAN_FRONTEND=noninteractive

# Install sudo (used in scripts that are tested)
RUN dnf -y install sudo

# Set timezone (used by pylint) and locale
ENV LANG=en_US.UTF-8  
ENV LANGUAGE=en_US:en  
ENV LC_ALL=en_US.UTF-8
ENV TZ=US/Central
RUN ln -snf /usr/share/zoneinfo/US/Central /etc/localtime && echo US/Central > /etc/timezone && \
    dnf -y install tzdata glibc-langpack-en
RUN localedef --verbose --force -i en_US -f UTF-8 en_US.UTF-8 || true

RUN mkdir /opt/LinuxLegionLaptop
WORKDIR /opt/LinuxLegionLaptop

COPY ./deploy/dependencies/install_test_dependencies_fedora.sh ./deploy/dependencies/install_test_dependencies_fedora.sh
RUN ./deploy/dependencies/install_test_dependencies_fedora.sh

# Test: Maybe refactor to run outside of Dockerfile
COPY deploy deploy
COPY tests tests
RUN ./deploy/package_testing/download_install_rpm_ppa.sh
#RUN ./tests/test_python_installed.sh
