name: Build PR
run-name: ${{ github.actor }} running Build PR
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Dependencies
      run: ./deploy/dependencies/install_dependencies_ubuntu.sh
      shell: bash
    - name: Build
      run: ./tests/test_kernel_build.sh
      shell: bash
    - name: Install
      run: ./tests/test_kernel_install.sh
      shell: bash

  run-kernel-module-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Dependencies
      run: ./deploy/dependencies/install_dependencies_ubuntu.sh
      shell: bash
    - name: Test Install
      run: ./tests/test_kernel_install.sh
      shell: bash
    - name: Test Reload First
      run: ./tests/test_kernel_reload.sh
      shell: bash
    - name: Test Reload Second
      run: ./tests/test_kernel_reload.sh
      shell: bash

  run-kernel-dkms-install-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Dependencies
      run: ./deploy/dependencies/install_dependencies_ubuntu.sh
      shell: bash
    - name: Build
      run: ./tests/test_kenel_dkms_install.sh || true
      shell: bash

  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run tests (Unbuntu 23.04)
      run: ./deploy/build_docker_ubuntu.sh
      shell: bash

  test-in-docker-container:
    needs: [build, run-tests]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build containers and run tests inside them
      run: ./deploy/build_containers.sh
      shell: bash
