name: Manual actions
on: 
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Dependencies
      run: ./deploy/dependencies/install_dependencies_ubuntu_24_04.sh
      shell: bash
    - name: Build
      run: ./tests/test_kernel_build.sh
      shell: bash
    - name: Install
      run: ./tests/test_kernel_install.sh
      shell: bash
  test-ci-env:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      with:
        ## limits ssh access and adds the ssh public key for the user which triggered the workflow
        limit-access-to-actor: true
        ## limits ssh access and adds the ssh public keys of the listed GitHub users
        limit-access-to-users: johnfanv2
